/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as BlocksIndexRouteImport } from './routes/blocks/index'
import { Route as DocsReactRouteImport } from './routes/docs/react'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChangelogSplatRouteImport } from './routes/changelog/$'
import { Route as BlocksBlockIdRouteImport } from './routes/blocks/$blockId'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as DocsReactIndexRouteImport } from './routes/docs/react/index'
import { Route as DocsReactSplatRouteImport } from './routes/docs/react/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChangelogRoute,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlocksRoute,
} as any)
const DocsReactRoute = DocsReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const ChangelogSplatRoute = ChangelogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ChangelogRoute,
} as any)
const BlocksBlockIdRoute = BlocksBlockIdRouteImport.update({
  id: '/$blockId',
  path: '/$blockId',
  getParentRoute: () => BlocksRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsReactIndexRoute = DocsReactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsReactRoute,
} as any)
const DocsReactSplatRoute = DocsReactSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsReactRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/legacy': typeof LegacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/blocks/$blockId': typeof BlocksBlockIdRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/react': typeof DocsReactRouteWithChildren
  '/blocks/': typeof BlocksIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/react/$': typeof DocsReactSplatRoute
  '/docs/react/': typeof DocsReactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legacy': typeof LegacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/blocks/$blockId': typeof BlocksBlockIdRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blocks': typeof BlocksIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/react/$': typeof DocsReactSplatRoute
  '/docs/react': typeof DocsReactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/legacy': typeof LegacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/blocks/$blockId': typeof BlocksBlockIdRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/react': typeof DocsReactRouteWithChildren
  '/blocks/': typeof BlocksIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/react/$': typeof DocsReactSplatRoute
  '/docs/react/': typeof DocsReactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/changelog'
    | '/docs'
    | '/legacy'
    | '/sitemap.xml'
    | '/api/og'
    | '/api/search'
    | '/blocks/$blockId'
    | '/changelog/$'
    | '/docs/$'
    | '/docs/react'
    | '/blocks/'
    | '/changelog/'
    | '/docs/'
    | '/docs/react/$'
    | '/docs/react/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legacy'
    | '/sitemap.xml'
    | '/api/og'
    | '/api/search'
    | '/blocks/$blockId'
    | '/changelog/$'
    | '/docs/$'
    | '/blocks'
    | '/changelog'
    | '/docs'
    | '/docs/react/$'
    | '/docs/react'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/changelog'
    | '/docs'
    | '/legacy'
    | '/sitemap.xml'
    | '/api/og'
    | '/api/search'
    | '/blocks/$blockId'
    | '/changelog/$'
    | '/docs/$'
    | '/docs/react'
    | '/blocks/'
    | '/changelog/'
    | '/docs/'
    | '/docs/react/$'
    | '/docs/react/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRouteWithChildren
  ChangelogRoute: typeof ChangelogRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LegacyRoute: typeof LegacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/docs/react': {
      id: '/docs/react'
      path: '/react'
      fullPath: '/docs/react'
      preLoaderRoute: typeof DocsReactRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/changelog/$': {
      id: '/changelog/$'
      path: '/$'
      fullPath: '/changelog/$'
      preLoaderRoute: typeof ChangelogSplatRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/blocks/$blockId': {
      id: '/blocks/$blockId'
      path: '/$blockId'
      fullPath: '/blocks/$blockId'
      preLoaderRoute: typeof BlocksBlockIdRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/react/': {
      id: '/docs/react/'
      path: '/'
      fullPath: '/docs/react/'
      preLoaderRoute: typeof DocsReactIndexRouteImport
      parentRoute: typeof DocsReactRoute
    }
    '/docs/react/$': {
      id: '/docs/react/$'
      path: '/$'
      fullPath: '/docs/react/$'
      preLoaderRoute: typeof DocsReactSplatRouteImport
      parentRoute: typeof DocsReactRoute
    }
  }
}

interface BlocksRouteChildren {
  BlocksBlockIdRoute: typeof BlocksBlockIdRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksBlockIdRoute: BlocksBlockIdRoute,
  BlocksIndexRoute: BlocksIndexRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

interface ChangelogRouteChildren {
  ChangelogSplatRoute: typeof ChangelogSplatRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogSplatRoute: ChangelogSplatRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

interface DocsReactRouteChildren {
  DocsReactSplatRoute: typeof DocsReactSplatRoute
  DocsReactIndexRoute: typeof DocsReactIndexRoute
}

const DocsReactRouteChildren: DocsReactRouteChildren = {
  DocsReactSplatRoute: DocsReactSplatRoute,
  DocsReactIndexRoute: DocsReactIndexRoute,
}

const DocsReactRouteWithChildren = DocsReactRoute._addFileChildren(
  DocsReactRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsReactRoute: typeof DocsReactRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsReactRoute: DocsReactRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRouteWithChildren,
  ChangelogRoute: ChangelogRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LegacyRoute: LegacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgRoute: ApiOgRoute,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
