name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm turbo run build --filter=@stepperize/react...

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: new release"
          title: "chore: new release"
          publish: pnpm ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
